import React from "react";
export const MONTHS=["Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"];
export const today=()=>new Date().toISOString().slice(0,10);
export const ym=(year,i)=>`${year}${String(i+1).padStart(2,"0")}`;
export const num=v=>Number(v||0);
export const unwrapJson=(response)=>{const row=response?.data?.data?.[0]; if(!row)return null; if(row.result){try{return JSON.parse(row.result)}catch{return row.result}} return row;};
export const permissionMode=item=>String(item?.permissionType||item?.permission||"FULL").toUpperCase();
export function StatusPill({value="Draft"}){const approved=value==="Approved",cancelled=value==="Cancelled";return <span className={`rounded-full px-3 py-1 text-xs font-semibold ${approved?'bg-emerald-100 text-emerald-700':cancelled?'bg-rose-100 text-rose-700':'bg-amber-100 text-amber-700'}`}>{value}</span>}
export function Field({label,children,className=""}){return <label className={`flex flex-col gap-1 text-xs font-medium text-slate-600 ${className}`}><span>{label}</span>{children}</label>}
export const inputClass="h-9 rounded-md border border-slate-300 bg-white px-2 text-sm outline-none focus:border-blue-500 disabled:bg-slate-100";
export function ActionBar({onNew,onSearch,onSave,onApprove,onCancel,locked,readOnly}){return <div className="flex flex-wrap gap-2 border-b bg-slate-50 p-2"><button className="global-button-ui" onClick={onNew}>New</button><button className="global-button-ui" onClick={onSearch}>Search</button><button className="global-button-ui" disabled={locked||readOnly} onClick={onSave}>Save</button><button className="global-button-ui" disabled={locked||readOnly} onClick={onApprove}>Approve</button><button className="global-button-ui" disabled={locked||readOnly} onClick={onCancel}>Cancel</button></div>}
export function ForecastGrid({rows,setRows,year,customer=false,locked=false}){const grouped=React.useMemo(()=>{const m=new Map();rows.forEach(r=>{const k=`${r.itemCode}|${r.itemName}|${r.uomCode}|${customer?r.custCode||'':''}`;if(!m.has(k))m.set(k,{...r,months:{}});m.get(k).months[r.forecastCutoff]=r.quantity});return [...m.values()]},[rows,customer]);const update=(g,i,value)=>{const period=ym(year,i);setRows(prev=>{const keyMatch=r=>r.itemCode===g.itemCode&&(!customer||r.custCode===g.custCode);const found=prev.some(r=>keyMatch(r)&&r.forecastCutoff===period);if(found)return prev.map(r=>keyMatch(r)&&r.forecastCutoff===period?{...r,quantity:num(value)}:r);return [...prev,{itemCode:g.itemCode,itemName:g.itemName,uomCode:g.uomCode,custCode:g.custCode||'',forecastCutoff:period,quantity:num(value),groupId:crypto.randomUUID?.()||String(Date.now())}]})};return <div className="overflow-auto"><table className="min-w-[1250px] w-full border-collapse text-xs"><thead><tr className="bg-slate-100"><th className="border p-2">Item Code</th><th className="border p-2 text-left">Item Description</th><th className="border p-2">UOM</th>{MONTHS.map(m=><th className="border p-2" key={m}>{m}</th>)}<th className="border p-2">Total</th></tr></thead><tbody>{grouped.map((g,ri)=><tr key={`${g.itemCode}-${ri}`}><td className="border p-1 text-center"><input disabled={locked} className={`${inputClass} w-28`} value={g.itemCode||''} onChange={e=>setRows(p=>p.map(r=>r.itemCode===g.itemCode?{...r,itemCode:e.target.value}:r))}/></td><td className="border p-1"><input disabled={locked} className={`${inputClass} w-full min-w-48`} value={g.itemName||''} onChange={e=>setRows(p=>p.map(r=>r.itemCode===g.itemCode?{...r,itemName:e.target.value}:r))}/></td><td className="border p-1"><input disabled={locked} className={`${inputClass} w-20`} value={g.uomCode||''} onChange={e=>setRows(p=>p.map(r=>r.itemCode===g.itemCode?{...r,uomCode:e.target.value}:r))}/></td>{MONTHS.map((_,i)=><td className="border p-1" key={i}><input type="number" disabled={locked} className={`${inputClass} w-20 text-right`} value={g.months[ym(year,i)]??0} onChange={e=>update(g,i,e.target.value)}/></td>)}<td className="border p-2 text-right font-semibold">{MONTHS.reduce((s,_,i)=>s+num(g.months[ym(year,i)]),0).toLocaleString()}</td></tr>)}</tbody></table></div>}
export function addBlankItem(setRows,year,custCode=""){const group=crypto.randomUUID?.()||String(Date.now());setRows(p=>[...p,...MONTHS.map((_,i)=>({itemCode:"",itemName:"",uomCode:"",custCode,forecastCutoff:ym(year,i),quantity:0,groupId:group}))])}
